### PR TITLE
feat: configure vite

### PR DESCRIPTION
**Pull request by Julien-R44**
- Replaces the `--encore` by `--bundler [vite, encore]`
- Add a prompt to select the bundler

image

### CODE REVIEW

**Comment by RomainLanz** [comment]
What if we want none?

Maybe we can ask first if people want an asset manager and then ask for the driver?

**Comment by Julien-R44** [comment]
Oops, you're right, I removed the possibility of not configuring an asset bundle. Thanks

**Comment by RomainLanz** [comment]
We could also add the option `I don't want to bundle my asset` and make it the default.

**Comment by Julien-R44** [comment]
that's what we do here, right? Or do you mean we should just rename the "None" option? 

image

**Comment by RomainLanz** [comment]
Oh yes, good like that!
The changes were not displayed when I was writing my message. 😄

**Comment by Julien-R44** [comment]
I'm closing because we will probably take a different approach for create-adonis-ts-app for v6

**Pull request closed without merging**
